---
title: Computing @ NYJC
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nyjc.computing@nyjc.edu.sg
description: Public page for NYJC's Computing programme and team
baseurl: ''
url: ''
twitter_username: 
github_username: nycomp
theme: monophase
plugins:
- jekyll-feed
google_analytics: G-RLM2EJYV9N
